"$schema" = 'https://starship.rs/config-schema.json'

format = """$username\
$directory\
$git_branch\
$git_status\
$git_state\
$character"""

right_format = """$python\
$golang\
$cmd_duration"""

[username]
disabled    = false
format      = "[$user]($style) "
show_always = true
style_user  = "green"

[directory]
truncation_length = 1
style             = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol   = "[❯](red)"
vimcmd_symbol  = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style  = "bright-black"

[git_status]
format = "([$all_status$ahead_behind]($style)) "
style  = "red"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style  = "red"

[cmd_duration]
format = "[$duration]($style) "
style  = "yellow"

[python]
format = "[$virtualenv.py]($style) "
style  = "bright-black"

[golang]
format = "[$version.go]($style) "
style  = "bright-black"
